version: '3'
services:
  app:
    build: .
    image: app-testing
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached
    env_file:
      .env.testing
  mysql:
     image: mysql:5.7
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_testing
     volumes:
      - ./my.cnf:/etc/mysql/conf.d/mysqlutf8.cnf
      - ./database/mysqldumps/app_testing.sql:/docker-entrypoint-initdb.d/app_testing.sql
  redis:
    image: redis:3.0
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
      - redis
    command: mysql:3306 redis:6379
